### ISSUE TITLE
Can't run: shows decode error:

### ISSUE THREAD

**Issue by aetherwu** [ipfs/py-ipfs-api#120]
Could anyone please help out on where to begin debug this error...?

python 3.6.4.2
ipfs version 0.4.11
latest ipfs-api

ipfs daemon is running correctly and its web gateway works properly.

PYTHON CODE
`
#!/usr/bin/python
#coding:UTF-8

import ipfsapi
api = ipfsapi.connect('127.0.0.1', 5001)
`

OUTPUT
`
Traceback (most recent call last):
  File "Untitled.py", line 5, in <module>
    api = ipfsapi.connect('127.0.0.1', 5001)
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/client.py", line 75, in connect
    assert_version(client.version()['Version'])
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/client.py", line 1849, in version
    return self._client.request('/version', decoder='json', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/http.py", line 37, in wrapper
    return func(self, *args, **merged)
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/http.py", line 170, in request
    files, headers, data)
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/http.py", line 116, in _request
    ret = parser.parse(res.content)
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/encoding.py", line 77, in parse
    results.extend(self.parse_finalize())
  File "/usr/local/lib/python3.6/site-packages/ipfsapi/encoding.py", line 254, in parse_finalize
    raise exceptions.DecodingError('json', self._lasterror)
ipfsapi.exceptions.DecodingError: Object decoding error: Expecting value: line 1 column 1 (char 0)
`

**Comment by aetherwu** [comment]
Found error on raw response:

`
Connection Closed

The requested URL could not be retrieved: 
http://127.0.0.1:5001/api/v0/version?stream-channels=true

Error descriptions:
Socket closed by remote peer
`

Solved:
Close local proxy.

However an error should be raised here properly.
