### ISSUE TITLE
python api connection error

### ISSUE THREAD

**Issue by crazychl** [ipfs/py-ipfs-api#134]
```python
api=ipfsapi.connect(host='localhost', port=5001, base='api/v0')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-08d1cc69a003> in <module>()
----> 1 api=ipfsapi.connect(host='localhost', port=5001, base='api/v0')

/usr/local/lib/python2.7/dist-packages/ipfsapi/client.pyc in connect(host, port, base, chunk_size, **defaults)
     73 
     74     # Query version number from daemon and validate it
---> 75     assert_version(client.version()['Version'])
     76 
     77     return client

/usr/local/lib/python2.7/dist-packages/ipfsapi/client.pyc in version(self, **kwargs)
   1876             dict : Daemon and system version information
   1877         """
-> 1878         return self._client.request('/version', decoder='json', **kwargs)
   1879 
   1880     def files_cp(self, source, dest, **kwargs):

/usr/local/lib/python2.7/dist-packages/ipfsapi/http.pyc in wrapper(self, *args, **kwargs)
     36         merged.update(self.defaults)
     37         merged.update(kwargs)
---> 38         return func(self, *args, **merged)
     39     return wrapper
     40 

/usr/local/lib/python2.7/dist-packages/ipfsapi/http.pyc in request(self, path, args, files, opts, stream, decoder, headers, data)
    243 
    244         return self._request(method, url, params, parser, stream,
--> 245                              files, headers, data)
    246 
    247     @pass_defaults

/usr/local/lib/python2.7/dist-packages/ipfsapi/http.pyc in _request(self, method, url, params, parser, stream, files, headers, data)
    189         else:
    190             # First decode received item
--> 191             ret = stream_decode_full(res, parser)
    192 
    193             # Raise exception for response status

/usr/local/lib/python2.7/dist-packages/ipfsapi/http.pyc in stream_decode_full(response, parser)
    113 def stream_decode_full(response, parser):
    114     with StreamDecodeIterator(response, parser) as response_iter:
--> 115         result = list(response_iter)
    116         if len(result) == 1:
    117             return result[0]

/usr/local/lib/python2.7/dist-packages/ipfsapi/http.pyc in next(self)
     85     #PY2: Old iterator syntax
     86     def next(self):
---> 87         return self.__next__()
     88 
     89     def __enter__(self):

/usr/local/lib/python2.7/dist-packages/ipfsapi/http.pyc in __next__(self)
     73 
     74             try:
---> 75                 data = next(self._response_iter)
     76 
     77                 # Create new parser iterator using the newly recieved data

/usr/lib/python2.7/dist-packages/requests/utils.pyc in iter_slices(string, slice_length)
    374     pos = 0
    375     while pos < len(string):
--> 376         yield string[pos:pos + slice_length]
    377         pos += slice_length
    378 
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by ncaew** [comment]
I meet same issue here:

```python

# python3 
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipfsapi
>>> ipfsClient = ipfsapi.connect('127.0.0.1', 5001)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/client.py", line 75, in connect
    assert_version(client.version()['Version'])
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/client.py", line 1878, in version
    return self._client.request('/version', decoder='json', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/http.py", line 38, in wrapper
    return func(self, *args, **merged)
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/http.py", line 245, in request
    files, headers, data)
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/http.py", line 191, in _request
    ret = stream_decode_full(res, parser)
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/http.py", line 115, in stream_decode_full
    result = list(response_iter)
  File "/usr/local/lib/python3.5/dist-packages/ipfsapi/http.py", line 75, in __next__
    data = next(self._response_iter)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 376, in iter_slices
    yield string[pos:pos + slice_length]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
>>> 

```

**Comment by ncaew** [comment]
In my case, to fix this issue is very easy:
```bash
pip3 install requests --upgrade
```
Run test code above again. It it OK.

I think the root cause is the the requests version is too old.
Before update requests, version is:
```bash
# pip3 show requests
---
Metadata-Version: 1.1
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
```

After update requests, version is:
```bash
# pip3 show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.19.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
```
Hope this will help.
